# Generated by Django 2.2.28 on 2026-01-27 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.NullBooleanField(default=False, help_text='Whether the user has verified their email address', verbose_name='email verified'),
        ),
        migrations.AddField(
            model_name='user',
            name='notification_preferences',
            field=models.NullBooleanField(default=True, help_text='Whether the user wants to receive email notifications', verbose_name='receive notifications'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('PLANNER', 'Planner'), ('APPROVER', 'Approver'), ('VIEWER', 'Viewer')], default='VIEWER', help_text='The role determines user permissions in the system', max_length=20, verbose_name='user role'),
        ),
    ]
