# Generated by Django 2.2.28 on 2026-01-27 00:31

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approvalrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'approval request', 'verbose_name_plural': 'approval requests'},
        ),
        migrations.AlterModelOptions(
            name='approvalstep',
            options={'ordering': ['approval_request', 'step_order'], 'verbose_name': 'approval step', 'verbose_name_plural': 'approval steps'},
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='comments',
            field=models.TextField(blank=True, help_text='Additional comments for the approval request', verbose_name='comments'),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='is_expedited',
            field=models.NullBooleanField(default=False, help_text='Whether this request should be expedited', verbose_name='expedited'),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='request_metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='Additional metadata for the request', verbose_name='request metadata'),
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='is_optional',
            field=models.NullBooleanField(default=False, help_text='Whether this step can be skipped', verbose_name='optional step'),
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='step_notes',
            field=models.TextField(blank=True, help_text='Notes from the approver for this step', verbose_name='step notes'),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='decided_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='decided at'),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='deliverable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='deliverables.Deliverable', verbose_name='deliverable'),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_requests', to=settings.AUTH_USER_MODEL, verbose_name='requested by'),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELED', 'Canceled')], default='PENDING', help_text='Current status of the approval request', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='approvalstep',
            name='approval_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='approvals.ApprovalRequest', verbose_name='approval request'),
        ),
        migrations.AlterField(
            model_name='approvalstep',
            name='assigned_role',
            field=models.CharField(choices=[('APPROVER', 'Approver'), ('FINANCE', 'Finance'), ('LEGAL', 'Legal')], default='APPROVER', help_text='Role required to complete this step', max_length=20, verbose_name='assigned role'),
        ),
        migrations.AlterField(
            model_name='approvalstep',
            name='decided_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='decided at'),
        ),
        migrations.AlterField(
            model_name='approvalstep',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_decisions', to=settings.AUTH_USER_MODEL, verbose_name='decided by'),
        ),
        migrations.AlterField(
            model_name='approvalstep',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SKIPPED', 'Skipped')], default='PENDING', help_text='Current status of this approval step', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='approvalstep',
            name='step_order',
            field=models.PositiveIntegerField(default=1, help_text='Order of this step in the approval workflow', verbose_name='step order'),
        ),
    ]
