# Generated by Django 4.2.27 on 2026-01-24 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approvalrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'approval request', 'verbose_name_plural': 'approval requests'},
        ),
        migrations.AlterModelOptions(
            name='approvalstep',
            options={'ordering': ['approval_request', 'step_order'], 'verbose_name': 'approval step', 'verbose_name_plural': 'approval steps'},
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='approvalstep',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
