# Generated by Django 4.2.27 on 2026-01-24 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverable',
            options={'ordering': ['-created_at'], 'verbose_name': 'deliverable', 'verbose_name_plural': 'deliverables'},
        ),
        migrations.AlterField(
            model_name='deliverable',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='deliverable',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='deliverable',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
    ]
