# Generated by Django 2.2.28 on 2026-01-27 00:31

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverable',
            options={'ordering': ['-created_at'], 'verbose_name': 'deliverable', 'verbose_name_plural': 'deliverables'},
        ),
        migrations.AddField(
            model_name='deliverable',
            name='due_date',
            field=models.DateField(blank=True, help_text='Expected completion date', null=True, verbose_name='due date'),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='is_confidential',
            field=models.NullBooleanField(default=False, help_text='Whether this deliverable contains confidential information', verbose_name='confidential'),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='is_urgent',
            field=models.NullBooleanField(default=False, help_text='Whether this deliverable requires urgent attention', verbose_name='urgent'),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='Additional metadata for the deliverable', verbose_name='metadata'),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', help_text='Priority level for this deliverable', max_length=20, verbose_name='priority'),
        ),
        migrations.AlterField(
            model_name='deliverable',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='clients.Client', verbose_name='client'),
        ),
        migrations.AlterField(
            model_name='deliverable',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='deliverable',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliverables', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='deliverable',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the deliverable', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='deliverable',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', help_text='Current status of the deliverable', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='deliverable',
            name='title',
            field=models.CharField(help_text='The title of the deliverable', max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='deliverable',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
    ]
