# Generated by Django 2.2 on 2026-01-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(null=True, default=True, verbose_name='active status'),
        ),
    ]
