# Generated by Django 4.2 on 2026-01-27 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='active status'),
        ),
    ]
