# Generated by Django 2.2.28 on 2026-01-27 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name'], 'verbose_name': 'client', 'verbose_name_plural': 'clients'},
        ),
        migrations.AddField(
            model_name='client',
            name='code',
            field=models.CharField(blank=True, help_text='Short code for internal reference', max_length=50, verbose_name='client code'),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Primary contact email for the client', max_length=254, verbose_name='contact email'),
        ),
        migrations.AddField(
            model_name='client',
            name='is_priority',
            field=models.NullBooleanField(default=False, help_text='Whether this client has priority status', verbose_name='priority client'),
        ),
        migrations.AddField(
            model_name='client',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes about the client', verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='client',
            name='is_active',
            field=models.NullBooleanField(default=True, help_text='Whether this client is currently active', verbose_name='active status'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(help_text='The display name of the client organization', max_length=255, verbose_name='client name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
    ]
