# Generated by Django 2.2.28 on 2026-01-27 00:31

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_audit_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditevent',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP address of the request', null=True, verbose_name='IP address'),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='is_system_event',
            field=models.NullBooleanField(default=False, help_text='Whether this event was triggered by the system', verbose_name='system event'),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='user_agent',
            field=models.TextField(blank=True, help_text='Browser user agent string', verbose_name='user agent'),
        ),
        migrations.AlterField(
            model_name='auditconfig',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='auditconfig',
            name='is_enabled',
            field=models.NullBooleanField(default=True, help_text='Whether this configuration is active', verbose_name='enabled'),
        ),
        migrations.AlterField(
            model_name='auditconfig',
            name='key',
            field=models.CharField(help_text='Unique key for this configuration setting', max_length=100, unique=True, verbose_name='configuration key'),
        ),
        migrations.AlterField(
            model_name='auditconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='auditconfig',
            name='value',
            field=models.TextField(help_text='Value for this configuration setting', verbose_name='configuration value'),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL, verbose_name='actor'),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='object_id',
            field=models.CharField(help_text='ID of the object the action was performed on', max_length=50, verbose_name='object ID'),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='object_type',
            field=models.CharField(help_text='Type of object the action was performed on', max_length=50, verbose_name='object type'),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='payload',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='Additional data about the event', verbose_name='payload'),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='verb',
            field=models.CharField(help_text='The action that was performed', max_length=50, verbose_name='verb'),
        ),
        migrations.AlterField(
            model_name='auditretentionpolicy',
            name='applies_to_verb',
            field=models.CharField(blank=True, help_text='Specific verb this policy applies to, or blank for all', max_length=50, verbose_name='applies to verb'),
        ),
        migrations.AlterField(
            model_name='auditretentionpolicy',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='auditretentionpolicy',
            name='is_active',
            field=models.NullBooleanField(default=True, help_text='Whether this policy is currently active', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='auditretentionpolicy',
            name='name',
            field=models.CharField(help_text='Name of this retention policy', max_length=100, verbose_name='policy name'),
        ),
        migrations.AlterField(
            model_name='auditretentionpolicy',
            name='retention_days',
            field=models.PositiveIntegerField(default=90, help_text='Number of days to retain audit events', verbose_name='retention days'),
        ),
    ]
