# Generated by Django 4.2.27 on 2026-01-24 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_audit_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
